# Form implementation generated from reading ui file 'social_media.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_6.setStyleSheet("background-color: #343541;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.output_window = QtWidgets.QListWidget(parent=self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.output_window.setFont(font)
        self.output_window.setStyleSheet("QListWidget {\n"
"    color: white;\n"
"}")
        self.output_window.setWordWrap(True)
        self.output_window.setObjectName("output_window")
        self.verticalLayout_16.addWidget(self.output_window)
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_7.setMinimumSize(QtCore.QSize(400, 0))
        self.frame_7.setStyleSheet("background-color: #343541;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MessageInput_2 = QtWidgets.QLineEdit(parent=self.frame_7)
        self.MessageInput_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.MessageInput_2.setStyleSheet("    QLineEdit {\n"
"        border: 2px solid #565869;\n"
"        border-radius: 10px;\n"
"        padding: 12px;\n"
"        font-size: 16px;\n"
"        background-color: #3B3B3B;\n"
"        color: #FFFFFF;\n"
"    }\n"
"\n"
"    QLineEdit::placeholder {\n"
"        color: #9CA3AF;\n"
"    }\n"
"\n"
"")
        self.MessageInput_2.setObjectName("MessageInput_2")
        self.horizontalLayout.addWidget(self.MessageInput_2)
        self.SendButton_2 = QtWidgets.QPushButton(parent=self.frame_7)
        self.SendButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #10A37F;\n"
"    color: #FFFFFF;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #13C59D;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #A0A0A0;  /* Grey background */\n"
"    color: #D3D3D3;  /* Light grey text color */\n"
"}\n"
"\n"
"QPushButton#SendButton {\n"
"    background-color: #19B797;\n"
"}\n"
"\n"
"QPushButton#SendButton:hover {\n"
"    background-color: #13C59D;\n"
"}\n"
"\n"
"QPushButton#SendButton:disabled {\n"
"    background-color: #A0A0A0;  /* Grey background for SendButton */\n"
"    color: #D3D3D3;  /* Light grey text color for SendButton */\n"
"}\n"
"")
        self.SendButton_2.setObjectName("SendButton_2")
        self.horizontalLayout.addWidget(self.SendButton_2)
        self.verticalLayout_16.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Social Media App"))
        self.MessageInput_2.setPlaceholderText(_translate("MainWindow", "Type a message..."))
        self.SendButton_2.setText(_translate("MainWindow", "Post"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
